using System.Collections.Generic;
using UnityEngine;

namespace CombatPrep.Core
{
    /// <summary>
    /// Every imported art asset the runtime uses, in one place: PBR surface materials, prop
    /// models, the sky and the soldier. Generated by CombatPrep > Rebuild Art Library
    /// (Editor/ArtBuilder), which also runs by itself whenever the source files in Assets/Art
    /// change.
    ///
    /// It lives in a Resources folder so it is loaded by name and always ships in a build -
    /// together with everything it references, which is what keeps the textured materials'
    /// shader variants alive without a keep-alive list. If it is missing, every caller falls
    /// back to the procedural look, so the game still runs from a bare checkout.
    /// </summary>
    public class ArtLibrary : ScriptableObject
    {
        [System.Serializable]
        public class Surface
        {
            public Material Material;
            /// <summary>Metres one repeat of the texture covers; meshes are UV'd to match.</summary>
            public float TileMeters = 2f;
            /// <summary>The texture's average colour - what chips and dust off it look like.</summary>
            public Color ImpactColor = Color.gray;
        }

        [System.Serializable]
        public class Prop
        {
            public GameObject Model;
            public Material Material;
            /// <summary>Real-world size in metres (x, y-up, z), used to sanity-check import scale.</summary>
            public Vector3 Size;
            public Color ImpactColor = Color.gray;
        }

        [System.Serializable]
        public class Character
        {
            /// <summary>The skinned model, with a Humanoid avatar on its Animator.</summary>
            public GameObject Prefab;
            /// <summary>
            /// Locomotion, crouch, fire and death, built from the Mixamo clips. Null until those
            /// have been downloaded - they aren't redistributable, so a fresh clone has none.
            /// </summary>
            public RuntimeAnimatorController Controller;
            public bool HasFire, HasDeath;
        }

        [Header("Surfaces")]
        public Surface Ground;
        public Surface Berm;
        public Surface Floor;
        public Surface Concrete;
        public Surface Rubble;
        public Surface ContainerA, ContainerB, ContainerC;
        public Surface SandbagA, SandbagB;
        public Surface Wood;
        public Surface Metal;

        [Header("Props")]
        public Prop Barrel;
        public Prop BurnBarrel;
        public Prop Barrier;
        public Prop Tyre;
        public Prop Crate;

        [Header("Sky")]
        public Texture Sky;
        public float SkyExposure = 0.12f;

        [Header("Characters")]
        public Character Soldier;

        /// <summary>Fingerprint of the source files this was built from; the builder compares it.</summary>
        [HideInInspector] public string SourceStamp;

        static ArtLibrary _instance;
        static bool _looked;

        /// <summary>The library, or null if none has been generated.</summary>
        public static ArtLibrary I
        {
            get
            {
                if (!_looked)
                {
                    _looked = true;
                    _instance = Resources.Load<ArtLibrary>("ArtLibrary");
                    if (_instance != null) _instance.RegisterImpactColors();
                }
                return _instance;
            }
        }

        void RegisterImpactColors()
        {
            foreach (var s in new[] { Ground, Berm, Floor, Concrete, Rubble, ContainerA, ContainerB, ContainerC,
                                      SandbagA, SandbagB, Wood, Metal })
                if (s != null && s.Material != null) SurfaceColors.Register(s.Material, s.ImpactColor);
            foreach (var p in new[] { Barrel, BurnBarrel, Barrier, Tyre, Crate })
                if (p != null && p.Material != null) SurfaceColors.Register(p.Material, p.ImpactColor);
        }

        public static bool Has(Surface s) => s != null && s.Material != null;
        public static bool Has(Prop p) => p != null && p.Model != null && p.Material != null;

        /// <summary>A character needs its animations too - a soldier frozen in a T-pose is worse than none.</summary>
        public static bool Has(Character c) => c != null && c.Prefab != null && c.Controller != null;
    }

    /// <summary>
    /// What a surface looks like when a bullet chips it. Flat-colour materials answer with
    /// their base colour; textured ones register the average of their texture here, because
    /// their base colour is only a tint.
    /// </summary>
    public static class SurfaceColors
    {
        static readonly Dictionary<Material, Color> Colors = new();

        public static void Register(Material m, Color c) => Colors[m] = c;

        public static Color For(Material m, Color fallback)
        {
            if (m == null) return fallback;
            if (Colors.TryGetValue(m, out var c)) return c;
            return m.HasProperty("_BaseColor") ? m.GetColor("_BaseColor") : fallback;
        }
    }
}
